# This configuration file allows our pre-commit hooks to be used with pre-commit: http://pre-commit.com/

- id: terraform-entry-sorter
  name: terraform-entry-sorter
  description: Check and fix certain terraform entry
  entry: hooks/terraform-entry-sorter.py
  pass_filenames: false
  always_run: true